version: '2'

services:
  frontend:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./frontend.conf:/etc/nginx/conf.d/default.conf:ro
  blue:
    image: nginx:alpine
    volumes:
      - ./blue.conf:/etc/nginx/conf.d/default.conf:ro
  green:
    image: nginx:alpine
    volumes:
      - ./green.conf:/etc/nginx/conf.d/default.conf:ro
